### ISSUE TITLE
ollydbg2-swig_wrap.c could not found.

### ISSUE THREAD

**Issue by realgam3** [0vercl0k/ollydbg2-python#10]
ollydbg2-swig_wrap.c is not in the git repository...
only its solution.

**Comment by 0vercl0k** [comment]
Please read carefully the build instructions here:
https://github.com/0vercl0k/ollydbg2-python -- that file is supposed to be
generated by SWIG automatically, that's why it's not in the git...

2015-04-15 13:15 GMT-07:00 RealGame (Tomer Zait) notifications@github.com:

**Comment by realgam3** [comment]
Thanks i will do it.

**Comment by 0vercl0k** [comment]
Great -- could you close the issue after then please =)?

2015-04-16 4:46 GMT-07:00 RealGame (Tomer Zait) notifications@github.com:
