### ISSUE TITLE
ollydb2-python: testingtestingtestingtesting!

### ISSUE THREAD

**Issue by 0vercl0k** [0vercl0k/ollydbg2-python#5]

**Comment by ghost** [comment]
Great work and an excellent plugin to ollydbg
But it seems it does not work on 64-bit systems
i use windows 8 pro 64bit & Py275
Plugin directory=C:\ollydbg\plugins
the plugin does not appear in plugin toolbar also does not appear in log 
i use ollydbg from https://github.com/0vercl0k/ollydbg2-python/blob/master/OllyDBG2-Python.7z
also i use The version from official  website 
i try to compiled source with visual studio but  appear  a lot of  error 
Thanks in advance
![capture](https://cloud.githubusercontent.com/assets/9021347/4516856/ce2e9808-4c0d-11e4-9b80-cd46d2be104c.PNG)

**Comment by 0vercl0k** [comment]
It works fine on my Win81 x64 machine with
https://github.com/0vercl0k/ollydbg2-python/blob/master/OllyDBG2-Python.7z
-- can you try to open _python_bindings_swig.pyd inside ollydbg please?
What happens when you do that?

Cheers,
0vercl0k

2014-10-04 22:32 GMT+01:00 sh3dow notifications@github.com:

**Comment by 0vercl0k** [comment]
Same thing with python-loader.dll by the way -- just to be sure the PE is
loadable on your system, if not we need to find why :)

2014-10-04 22:41 GMT+01:00 0vercl0k 0vercl0k@tuxfamily.org:

**Comment by ghost** [comment]
![capture2](https://cloud.githubusercontent.com/assets/9021347/4516898/3b8896cc-4c10-11e4-8328-637cb2e77363.PNG)

**Comment by 0vercl0k** [comment]
OK -- This is what I thought: this module has been linked with python27.dll
which means you need Python27 x86 to make it works :)

2014-10-04 22:50 GMT+01:00 sh3dow notifications@github.com:

**Comment by ghost** [comment]
i use Python27 x86

**Comment by 0vercl0k** [comment]
Do you have Python27 x86 in your PATH? If not, python27.dll won't be found
when you load the .pyd module

2014-10-04 23:02 GMT+01:00 sh3dow notifications@github.com:

**Comment by ghost** [comment]
C:\Python27
![capture3](https://cloud.githubusercontent.com/assets/9021347/4516928/f0601bd6-4c12-11e4-8add-3281a5966c7d.PNG)

**Comment by 0vercl0k** [comment]
In your PATH environment variable I meant :)

2014-10-04 23:08 GMT+01:00 sh3dow notifications@github.com:

**Comment by ghost** [comment]
Thank you 0vercl0k for helping me now it work after installing Visual C++ Redistributable for Visual Studio 2012 Update 4  for both 32 & 64 
http://www.microsoft.com/en-us/download/details.aspx?id=30679#

In the past, I have Visual C++ Redistributable for Visual Studio 2010 both 32& 64  (are you compile plugin in Higher version of Visual Studio 2010)

---

Is it possible to write more scripts

**Comment by 0vercl0k** [comment]
Cool, no worries :)

2014-10-04 23:31 GMT+01:00 sh3dow notifications@github.com:

**Comment by ghost** [comment]
Question Do I need to compile the python-loader.dll despite it already being built? I suppose the main question is I have everything in the proper directories  

├───Data
├───Libs
├───ollyapi
└───plugins
    └───multiasm

C:\Users\Bob\Desktop\Olly>

and yes x86 python is installed and is in path.

C:\Users\ApertureSecurity\Desktop\Olly\ollyapi>C:\Users\ApertureSecurity\Desktop
\Olly\ollyapi\python_bindings_swig.pyc
Traceback (most recent call last):
  File "D:\Codes\OllyDBG2-Python\ollyapi\python_bindings_swig.py", line 28, in <
module>
    _python_bindings_swig = swig_import_helper()
  File "D:\Codes\OllyDBG2-Python\ollyapi\python_bindings_swig.py", line 24, in s
wig_import_helper
    _mod = imp.load_module('_python_bindings_swig', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.

C:\Users\ApertureSecurity\Desktop\Olly\ollyapi>python
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.

> > > quit()

To me it looks like it cannot find the dll and I have the dll in /Olly/plugins/

Surely this is something small that I am missing and if there it helps, I am on win7 x64

**Comment by 0vercl0k** [comment]
The important things to have are:
1. Python 2.7 32 bits installed
2. SWIG bindings built: _python_bindings_swig.pyd (that file is
   basically a dll & that's the one python_bindings_swig.py will load)

It seems you don't have _python_bindings_swig.pyd available ; to install
properly everything, please follow my notes here:
https://github.com/0vercl0k/ollydbg2-python

Hoping this helps!
Cheers,
Axel

2015-03-12 17:15 GMT-07:00 ApertureSecurity notifications@github.com:

**Comment by ghost** [comment]
Sorry for the late reply.I wanted to try to figure things out for a bit.  I had to install swig to the ollydbg directory to make the plugin visible. The only thing is that the scripts lead to crashes (looks like memory access violations). Also the command bar seems to have no purpose , although I haven't been able to get this to do anything yet. if you want the crash dump from olly I can provide this. let me know if you want anything else.

thanks

**Comment by 0vercl0k** [comment]
In which module do you get a crash?

2015-03-19 17:05 GMT-07:00 ApertureSecurity notifications@github.com:

**Comment by ghost** [comment]
here is the error log. 
http://pastebin.com/YYt8CiRP

I think this was from the swig binding so I re ran the  generate_python_module.bat

and now olly doesn't crash. However, I cannot tell if the plugin is working or not. I am sure that at this point there is some kind of user error or lacking understand in how this plugin was intended to run. How am I supposed to use this? it looks like I should just load the script and I should see a window provide out put. Also how is the command window supposed to work?

**Comment by 0vercl0k** [comment]
If the plugin works you'll know about it you either look at the log window
where it is supposed to output debug messages, or in the plugin menu where
you will be able to load your script (shortcut = alt+f7). The command
window is _less_ stable than all the other things (which are quite unstable
too) -- so I would advise to not use it : - D.

2015-03-19 23:51 GMT-07:00 ApertureSecurity notifications@github.com:

**Comment by ghost** [comment]
It loads just fine, it seems but I need to understand how to use this. Did I understand correctly that the output from the plugin is supposed be in the logs? Take a look please and advise on if the plugin appears to have run correctly.

thanks

http://pastebin.com/XEHeZMqR

**Comment by 0vercl0k** [comment]
1.           [python-loader] Trying to execute the script located here:
   'C:\Users\ApertureSecurity\Desktop\ollydbg2-python\samples\testing\testing.py'..
2.           [python-loader] Execution is done!

That sounds like good to me

2015-03-22 19:13 GMT-07:00 ApertureSecurity notifications@github.com:

**Comment by ghost** [comment]
Oh I looked at your default output and mine contains only what I provided to you in the pastebin . In other words, I only get an announcement for the starting and ending executions, nothing more.

**Comment by 0vercl0k** [comment]
Well, if you don't print anything in your script, you won't have any output
in the log yeah -- could you show me your script?

2015-03-22 23:10 GMT-07:00 ApertureSecurity notifications@github.com:

**Comment by ghost** [comment]
I was running the testing.py that comes with this repo .

**Comment by 0vercl0k** [comment]
OK -- so in that case I guess the *stdout *hooker fails for some reasons ;
to debug this issue I suggest you add something like "open('foo',
'w').write('before importing')" inside the **init**.py in the ollyapi
directory. You can add one after each import. The usual error is to have a
"bad" _python_bindings_swig.pyd, so every imports fail inside the
__init__.py file which means the stdout hooker isn't instanciated so you
don't get any feedback in the console window.

2015-03-23 14:01 GMT-07:00 ApertureSecurity notifications@github.com:
