### ISSUE TITLE
How to build working OllyDbg2-Python Plugin?

### ISSUE THREAD

**Issue by pbelskiy** [0vercl0k/ollydbg2-python#8]
Where i can get "python_bindings_swig.pyd" ? 
ImportError: No module named python_bindings_swig

And why you can't upload compiled working version? Maybe you can give me your full archive of OllyDbg2 with Python Plugin? =\

**Comment by Hanan-Natan** [comment]
There is a directory named swig in there a file named generate_python_module.bat it should create the pyd file.

This file should run automatically (as a Pre-Build Event) when you build your project using VS, however it doesn't work on all systems since the generate_python_module.bat batch try to run python directly...

In order to correct it just edit the generate_python_module.bat batch and append the full path to the python.exe file, like c:\Python27\python.exe. Then build the swig project.

**Comment by pbelskiy** [comment]
I have't this file "generate_python_module.bat", why i can't use your compiled version?

**Comment by 0vercl0k** [comment]
I just put together an archive with the binaries I use -- use them at your
own risk:
https://github.com/0vercl0k/ollydbg2-python/raw/master/OllyDBG2-Python.7z

0vercl0k

2014-07-08 14:48 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
Your build dont work, OllyDbg can't see plugin.

**Comment by 0vercl0k** [comment]
It can. Just configure correctly the path of the plugins, the udds & stuff

2014-07-08 14:58 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
I have correctly path to plugin, but Plugin don't load, check it yourself

**Comment by pbelskiy** [comment]
I use your OllyDbg in your archive, 2.01

**Comment by 0vercl0k** [comment]
Works correctly here :/

2014-07-08 15:02 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
http://rghost.ru/56787848/image.png, Plugins are gray

**Comment by 0vercl0k** [comment]
Have you some log messages in the log window? Are you able to load the .dll
inside OllyDbg?

2014-07-08 15:09 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
I reboot my Windows and now all good, thanks a lot !

**Comment by pbelskiy** [comment]
It's strange, your build first time can't see your plugin, after reboot all good (Windows 7 x64), on VirtualBox Windows XP SP3, same error first time, after reboot too... 

I think it's because MSVCR110.dll not exists in my Windows XP, can you rebuild plugin without its dependence?

And where is python.h, VS can't find it when i compile python-loader

**Comment by 0vercl0k** [comment]
Python.h is shipped with Python :).
I suggest to build the dll yourself if you want to run it on outdated OS, I put together some notes etc. It should be fairly easy to do ; just follow https://github.com/0vercl0k/ollydbg2-python#Installation.

**Comment by pbelskiy** [comment]
Ok, I will try, but maybe you build public dll plugin for all without MSVS dll dependens, much users want working archive without self compiling. :)

Added: i compiled for Win7, but in WinXP x86 your plugins dont work :(

**Comment by pbelskiy** [comment]
Project have bug, i compiled for WinXP, and plugin dot't print any information from script, only Succcess executed script!

**Comment by 0vercl0k** [comment]
Which version of Python are you using ? Can I see the script you are trying
to execute?

2014-07-09 11:35 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
It's simple script "upx_oep", i said about Windows XP not working, first it's because WinXP kernel32.dll have't GetTickCount64, i change it to GetTickCount, and library are run, but, not print script messages, only two plugin messages: "Try execute", "Execute done". I think it's maybe because on windows XP ollyapi folder is bad?

**Comment by 0vercl0k** [comment]
Could you try with a simple script doing a single "print 'something'"?

2014-07-09 11:56 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
Only this, but on Win7 plugin print script messages.

[python-loader] Trying to execute the script located here: 'F:\ollydbg2-python-master\samples\testing\testing.py'..
 [python-loader] Execution is done!

**Comment by 0vercl0k** [comment]
Another idea would be to write into a file, to exactly know where exactly
the issue is: either the Python hooker (and in that case it means the
Python script is executed), or that the Python scripts aren't executed at
all

2014-07-09 12:02 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
Script:
from ollyapi import *

def main():
    with open('test.txt', 'w') as f:
        f.write('Hello world')
    print 'Aight, ready for the demonstration'

Log:
Address   Message
          [python-loader] Trying to execute the script located here: 'C:\testing\testing.py'..
          [python-loader] Execution is done!

And not exist file.

**Comment by 0vercl0k** [comment]
And without the "from ollyapi import *" ?

2014-07-09 12:12 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
def main():
    with open('test.txt', 'w') as f:
        f.write('Hello world')
    print 'Aight, ready for the demonstration'

Log data
Address   Message
          [python-loader] Trying to execute the script located here: 'C:\testing\testing.py'..
          [python-loader] Execution is done!

Havent file

**Comment by 0vercl0k** [comment]
if you want main() to be called, you have to add a line to actually call it
:D add a main()

2014-07-09 12:23 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
File created, but message i have't

**Comment by 0vercl0k** [comment]
Great ; so now can you try to load in OllyDbg the file
'_python_bindings_swig.pyd' ? This is a simple DLL module ; maybe the file
can't be loaded on WinXP for similar reasons you described & this would be
an explanation why 'from ollyapi import *' would fail

2014-07-09 12:27 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
'_python_bindings_swig.pyd' succesfull loaded in OllyDbg in my Windows XP

**Comment by pbelskiy** [comment]
I have same problem https://github.com/0vercl0k/ollydbg2-python/issues/6, with import ollyapi not work too.

**Comment by 0vercl0k** [comment]
This can't be the same issue no. Can you add some debug output inside the
**init**.py file to know at which point it fails?

2014-07-09 12:48 GMT+02:00 nerv0us notifications@github.com:

**Comment by pbelskiy** [comment]
Problew was because i was copy invalid ollyapi to C:\Python27\lib, when i delete it, scripts begin using valid your ollyapi form OllyDbg folder, now work fine, thanks.
